### ISSUE TITLE
Confusing "Perl" SRPM for rubygem-thin

### ISSUE THREAD

**Issue by voxik** [minimization/content-resolver-input#354]
Looking at [rubygem-thin](https://tiny.distro.builders/view-rpm--view-eln--rubygem-thin.html), I am not completely sure why there is refered "SRPM perl", that appears to be some error.

**Comment by voxik** [comment]
Hm, there si more suspicious content:

https://tiny.distro.builders/view-srpm--view-eln--rubygem-RedCloth.html

**Comment by asamalik** [comment]
That is a bug. Content Resolver currently doesn't get links between RPMs and SRPMs for buildroot-only packages. (They're resolved in an external tool, because it needs to rebuild SRPMs for each architecture, and that's beyond what Content Resolver can do.)

I've fixed it, which unfortunately means it just won't show any SRPM for these packages at the moment.

This also explains your second comment — that'll be a buildroot-only SRPM, which doesn't have its links to RPMs.

But I'll look into this to see how I can get that information and show it properly.

**Comment by asamalik** [comment]
I've added the missing link between RPMs and SRPMs for buildroot packages.

**Comment by voxik** [comment]
LGTM, thx.
